# Generated by Django 4.1 on 2022-11-06 14:54

from django.db import migrations, models
import valavio.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[valavio.common.validators.MinLengthValidator(2), valavio.common.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[valavio.common.validators.MinLengthValidator(2), valavio.common.validators.validate_only_letters])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
            ],
        ),
    ]
